title: Everton Castro
description: > # this means to ignore newlines until "baseurl:"
  ConteÃºdo sobre desenvolvimento de sistemas. InÃ­cio de carreira em tecnologia e compartilhamento de experiÃªncias de estudo.
permalink: ':title/'
baseurl: "/"
url: "https://www.evertoncastro.com"
site-twitter:

# Author Settings
author: Everton Castro
author-img: me.jpg
about-author: Desenvovedor Full Stack, fÃ£ de podcasts, canais e livros de tecnologia. <br/>ğŸ§ğŸ’»ğŸ“š
social-twitter: evertonCastroSP
social-facebook: everton.decastro.12
social-github: evertoncastro
social-linkedin: evertonfatecit
social-email: evertoncastro.sp@gmail.com

# Disqus
discus-identifier: evertoncastro

# Tracker
analytics: UA-121170851-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-sitemap

paginate: 4
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
