title: Everton
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter:

# Author Settings
author: Everton Castro
author-img: me.jpg
about-author: Sou desenvolvedor de sistemas e fÃ£ de podcasts e blogs de diversos assuntos. <br/>E claro, amo tecnologia. ðŸ’»ðŸ¤“
social-twitter: evertonCastroSP
social-facebook: everton.decastro.12
social-github: evertoncastro
social-linkedin: evertonfatecit
social-email: evertoncastro.sp@gmail.com

# Disqus
discus-identifier: evertoncastro

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 1
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
